#!/bin/bash

. ./test_lib.sh

new_key A
new_key B

start_server A 10000 5000 127.0.0.1:5001
start_server B 10001 5001 127.0.0.1:5000

new_poll 10000 "What's the time?" "11:48:37" "Soon food!" "Time is an human construct"

log_wait B "Poll A0"
